name: SST deploy (dev)

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: sst-deploy-dev
  cancel-in-progress: true

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SST_STAGE: dev
      # Region is set in sst.config.ts; keep here for clarity if needed by AWS SDK defaults
      AWS_REGION: us-east-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Configure AWS credentials (OIDC)
        # Supply the role ARN after IAM/OIDC is configured in AWS account 905418078159
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build resolvers
        run: pnpm run build:resolvers

      - name: Deploy SST app (dev)
        run: pnpm run deploy -- --stage dev
