name: SST destroy (dev)

on:
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      SST_STAGE: dev
      AWS_REGION: us-east-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # Use the version declared in package.json "packageManager" (pnpm@10.15.0)
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-2

      - name: Destroy SST app (dev)
        run: pnpm run remove -- --stage dev
